"use client";

import { useId, type ReactNode } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { TableScroll } from "@/components/ui/table-scroll";
import { formatCompactCurrency, formatCurrency } from "@/lib/sample-data";
import { CAP_RATE_MINIMUM_SAMPLE, type DashboardData } from "@/lib/types";

function ChartData({ label, columns, rows }: { label: string; columns: string[]; rows: string[][] }) {
  return <details className="mt-5 border-t border-line pt-4"><summary className="cursor-pointer text-xs font-semibold text-navy">View chart data as a table</summary><TableScroll className="mt-4 border border-line" label={label}><table className="w-full min-w-[480px] border-collapse text-left text-xs"><thead><tr className="bg-mist text-slate">{columns.map((column) => <th className="px-3 py-2 font-semibold" key={column} scope="col">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr className="border-t border-line" key={`${row[0]}-${rowIndex}`}>{row.map((cell, cellIndex) => cellIndex === 0 ? <th className="px-3 py-2 font-semibold text-navy" key={`${cell}-${cellIndex}`} scope="row">{cell}</th> : <td className="px-3 py-2 text-slate" key={`${cell}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></TableScroll></details>;
}

function ChartFrame({ eyebrow, title, sample, description, dataTable, children }: { eyebrow: string; title: string; sample: string; description: string; dataTable: ReactNode; children: ReactNode }) {
  const id = useId();
  return <section className="panel min-w-0 p-5 sm:p-7"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold text-navy" id={`${id}-title`}>{title}</h2></div><span className="tag shrink-0">{sample}</span></div><p className="mt-3 text-xs leading-5 text-slate" id={`${id}-description`}>{description}</p><div aria-describedby={`${id}-description`} aria-labelledby={`${id}-title`} className="mt-7 h-[280px] w-full">{children}</div>{dataTable}</section>;
}

const currencyTick = (value: number) => formatCompactCurrency(value);
const numberTick = (value: number) => String(value);

export function DashboardCharts({ data }: { data: DashboardData }) {
  const marketRows = data.medianPricePerSqFtByMarket.slice(0, 8);
  return <div className="grid gap-5 lg:grid-cols-2">
    <ChartFrame eyebrow="Activity" title="Transaction count over time" sample={`n = ${data.metrics.transactionCount}`} description="Recorded transactions grouped by sale month within the selected filters." dataTable={<ChartData label="Transaction count over time data" columns={["Month", "Transactions"]} rows={data.transactionCountOverTime.map((point) => [point.label, String(point.transactionCount)])} />}><ResponsiveContainer height="100%" width="100%"><LineChart accessibilityLayer data={data.transactionCountOverTime} margin={{ top: 10, right: 12, left: -12, bottom: 8 }}><CartesianGrid stroke="#dce1e3" vertical={false} /><XAxis axisLine={false} dataKey="label" tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><YAxis allowDecimals={false} axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickFormatter={numberTick} tickLine={false} /><Tooltip /><Line activeDot={{ r: 5 }} dataKey="transactionCount" dot={{ fill: "#9a5b3d", r: 3 }} name="Transactions" stroke="#10263d" strokeWidth={2} type="monotone" /></LineChart></ResponsiveContainer></ChartFrame>

    <ChartFrame eyebrow="Sales volume" title="Volume by property type" sample={`n = ${data.metrics.transactionCount}`} description="Aggregate fictional or stored sale prices by controlled property type." dataTable={<ChartData label="Sales volume by property type data" columns={["Property type", "Transactions", "Sales volume"]} rows={data.salesVolumeByPropertyType.map((point) => [point.propertyType, String(point.transactionCount), formatCurrency(point.salesVolume)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={data.salesVolumeByPropertyType} margin={{ top: 10, right: 12, left: 4, bottom: 28 }}><CartesianGrid stroke="#dce1e3" vertical={false} /><XAxis angle={-25} axisLine={false} dataKey="propertyType" height={55} textAnchor="end" tick={{ fill: "#607080", fontSize: 10 }} tickLine={false} /><YAxis axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickFormatter={currencyTick} tickLine={false} /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Bar dataKey="salesVolume" fill="#10263d" name="Sales volume" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame>

    <ChartFrame eyebrow="Pricing" title="Median price per square foot by market" sample={`n = ${data.metrics.pricePerSqFtSampleSize}`} description="Each market label is accompanied by its usable price-per-square-foot record count." dataTable={<ChartData label="Median price per square foot by market data" columns={["Market", "Median price / sq. ft.", "Usable records"]} rows={marketRows.map((point) => [point.market, formatCurrency(point.medianPricePerSqFt), String(point.sampleSize)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={marketRows} layout="vertical" margin={{ top: 5, right: 24, left: 28, bottom: 5 }}><CartesianGrid horizontal={false} stroke="#dce1e3" /><XAxis axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickFormatter={(value) => formatCurrency(Number(value))} tickLine={false} type="number" /><YAxis axisLine={false} dataKey="market" tick={{ fill: "#607080", fontSize: 10 }} tickLine={false} type="category" width={100} /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Bar dataKey="medianPricePerSqFt" fill="#607080" name="Median price / sq. ft." radius={[0, 2, 2, 0]} /></BarChart></ResponsiveContainer></ChartFrame>

    {data.capRateDistribution.length ? <ChartFrame eyebrow="Reported cap rates" title="Cap-rate distribution" sample={`n = ${data.metrics.capRateSampleSize}`} description="Only reported values are included; bins are hidden below the minimum sample threshold." dataTable={<ChartData label="Reported cap-rate distribution data" columns={["Cap-rate range", "Transactions"]} rows={data.capRateDistribution.map((bin) => [bin.label, String(bin.count)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={data.capRateDistribution} margin={{ top: 10, right: 12, left: -12, bottom: 8 }}><CartesianGrid stroke="#dce1e3" vertical={false} /><XAxis axisLine={false} dataKey="label" tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><YAxis allowDecimals={false} axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><Tooltip /><Bar dataKey="count" fill="#9a5b3d" name="Transactions" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame> : <section className="panel grid min-h-[410px] place-items-center p-8 text-center"><div><p className="eyebrow">Reported cap rates</p><h2 className="mt-3 text-xl font-semibold text-navy">Insufficient sample</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate">Cap-rate statistics require at least {CAP_RATE_MINIMUM_SAMPLE} usable observations. The current filters return {data.metrics.capRateSampleSize}.</p></div></section>}
  </div>;
}
