"use client";

import { useId, type ReactNode } from "react";
import { ShieldAlert } from "lucide-react";
import { useReducedMotion } from "motion/react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { TableScroll } from "@/components/ui/table-scroll";
import { formatCount } from "@/lib/count-label";
import { formatCompactCurrency, formatCurrency } from "@/lib/sample-data";
import { CAP_RATE_MINIMUM_SAMPLE, type DashboardData } from "@/lib/types";

function ChartData({ label, columns, rows }: { label: string; columns: string[]; rows: string[][] }) {
  return <details className="mt-5 border-t border-line pt-4"><summary className="cursor-pointer text-xs font-semibold text-navy">View accessible data table</summary><TableScroll className="mt-4 border border-line" label={label}><table className="w-full min-w-[480px] border-collapse text-left text-xs"><thead><tr className="bg-mist text-slate">{columns.map((column) => <th className="px-3 py-2 font-semibold" key={column} scope="col">{column}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr className="border-t border-line" key={`${row[0]}-${rowIndex}`}>{row.map((cell, cellIndex) => cellIndex === 0 ? <th className="px-3 py-2 font-semibold text-navy" key={`${cell}-${cellIndex}`} scope="row">{cell}</th> : <td className="px-3 py-2 text-slate" key={`${cell}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></TableScroll></details>;
}

function ChartFrame({ index, eyebrow, title, sample, description, dataTable, children, chartHeight = "h-[270px] sm:h-[300px]" }: { index: string; eyebrow: string; title: string; sample: string; description: string; dataTable: ReactNode; children: ReactNode; chartHeight?: string }) {
  const id = useId();
  return <section className="panel min-w-0 p-5 sm:p-7"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-2 font-serif text-2xl font-medium text-navy" id={`${id}-title`}>{title}</h2></div><div className="text-right"><span aria-hidden="true" className="block font-mono text-[9px] text-line">{index}</span><span className="tag mt-2 shrink-0">{sample}</span></div></div><p className="mt-3 max-w-xl text-xs leading-5 text-slate" id={`${id}-description`}>{description}</p><div aria-describedby={`${id}-description`} aria-labelledby={`${id}-title`} className={`mt-7 w-full ${chartHeight}`}>{children}</div>{dataTable}</section>;
}

function UnavailableChart({ index, eyebrow, title, description }: { index: string; eyebrow: string; title: string; description: string }) {
  return <section className="panel grid min-h-[430px] place-items-center p-8 text-center"><div><span aria-hidden="true" className="font-mono text-[9px] text-line">{index}</span><p className="eyebrow mt-4">{eyebrow}</p><h2 className="mt-3 font-serif text-2xl font-medium text-navy">{title}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate">{description}</p></div></section>;
}

const currencyTick = (value: number) => formatCompactCurrency(value);
const numberTick = (value: number) => String(value);
const tooltipStyle = { backgroundColor: "#fffdfa", border: "1px solid #d7d2c8", borderRadius: 0, boxShadow: "0 14px 34px rgba(7,26,44,0.12)", color: "#0a2338", fontSize: 12 };

export function DashboardCharts({ data }: { data: DashboardData }) {
  const reduceMotion = useReducedMotion();
  const animate = !reduceMotion;
  const marketRows = data.medianPricePerSqFtByMarket.slice(0, 8);

  return <section aria-labelledby="dashboard-charts-title"><div className="mb-6"><p className="eyebrow">Market exhibits</p><h2 className="mt-2 font-serif text-3xl font-medium text-navy" id="dashboard-charts-title">Patterns inside the filtered sample</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate">Hover or focus for exact values. Each exhibit also includes an accessible source table.</p></div><div className="grid gap-5 xl:grid-cols-2">
    <ChartFrame index="01" eyebrow="Activity" title="Transaction count over time" sample={formatCount(data.metrics.transactionCount, "record")} description="Recorded transactions grouped by sale month within the selected filters." dataTable={<ChartData label="Transaction count over time data" columns={["Month", "Transactions"]} rows={data.transactionCountOverTime.map((point) => [point.label, String(point.transactionCount)])} />}><ResponsiveContainer height="100%" width="100%"><LineChart accessibilityLayer data={data.transactionCountOverTime} margin={{ top: 10, right: 12, left: -12, bottom: 8 }}><CartesianGrid stroke="#dce1e3" vertical={false} /><XAxis axisLine={false} dataKey="label" interval="preserveStartEnd" tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><YAxis allowDecimals={false} axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickFormatter={numberTick} tickLine={false} /><Tooltip contentStyle={tooltipStyle} cursor={{ stroke: "#cb6846", strokeWidth: 1 }} /><Line activeDot={{ r: 5 }} animationDuration={650} dataKey="transactionCount" dot={{ fill: "#ae4f31", r: 3 }} isAnimationActive={animate} name="Transactions" stroke="#0a2338" strokeWidth={2.5} type="monotone" /></LineChart></ResponsiveContainer></ChartFrame>

    <ChartFrame index="02" eyebrow="Sales volume" title="Volume by property type" sample={formatCount(data.metrics.transactionCount, "record")} description="Aggregate fictional or stored sale prices by controlled property type." chartHeight="h-[310px] sm:h-[330px]" dataTable={<ChartData label="Sales volume by property type data" columns={["Property type", "Transactions", "Sales volume"]} rows={data.salesVolumeByPropertyType.map((point) => [point.propertyType, String(point.transactionCount), formatCurrency(point.salesVolume)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={data.salesVolumeByPropertyType} layout="vertical" margin={{ top: 5, right: 22, left: 20, bottom: 5 }}><CartesianGrid horizontal={false} stroke="#dce1e3" /><XAxis axisLine={false} tick={{ fill: "#607080", fontSize: 10 }} tickFormatter={currencyTick} tickLine={false} type="number" /><YAxis axisLine={false} dataKey="propertyType" tick={{ fill: "#607080", fontSize: 10 }} tickLine={false} type="category" width={96} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgba(203,104,70,0.08)" }} formatter={(value) => formatCurrency(Number(value))} /><Bar animationDuration={650} dataKey="salesVolume" fill="#0a2338" isAnimationActive={animate} name="Sales volume" radius={[0, 2, 2, 0]} /></BarChart></ResponsiveContainer></ChartFrame>

    {marketRows.length ? <ChartFrame index="03" eyebrow="Pricing" title="Median price per square foot by market" sample={formatCount(data.metrics.pricePerSqFtSampleSize, "usable record")} description="Each market label is accompanied by its usable price-per-square-foot record count." dataTable={<ChartData label="Median price per square foot by market data" columns={["Market", "Median price / sq. ft.", "Usable records"]} rows={marketRows.map((point) => [point.market, formatCurrency(point.medianPricePerSqFt), String(point.sampleSize)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={marketRows} layout="vertical" margin={{ top: 5, right: 24, left: 24, bottom: 5 }}><CartesianGrid horizontal={false} stroke="#dce1e3" /><XAxis axisLine={false} tick={{ fill: "#607080", fontSize: 10 }} tickFormatter={(value) => formatCurrency(Number(value))} tickLine={false} type="number" /><YAxis axisLine={false} dataKey="market" tick={{ fill: "#607080", fontSize: 10 }} tickLine={false} type="category" width={104} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgba(203,104,70,0.08)" }} formatter={(value) => formatCurrency(Number(value))} /><Bar animationDuration={650} dataKey="medianPricePerSqFt" fill="#607080" isAnimationActive={animate} name="Median price / sq. ft." radius={[0, 2, 2, 0]} /></BarChart></ResponsiveContainer></ChartFrame> : <UnavailableChart index="03" eyebrow="Pricing" title="Price-per-square-foot data unavailable" description="The filtered records do not contain both a sale price and usable building area." />}

    {data.capRateDistribution.length ? <ChartFrame index="04" eyebrow="Reported cap rates" title="Cap-rate distribution" sample={formatCount(data.metrics.capRateSampleSize, "reported record")} description="Only reported values are included; bins are hidden below the minimum sample threshold." dataTable={<ChartData label="Reported cap-rate distribution data" columns={["Cap-rate range", "Transactions"]} rows={data.capRateDistribution.map((bin) => [bin.label, String(bin.count)])} />}><ResponsiveContainer height="100%" width="100%"><BarChart accessibilityLayer data={data.capRateDistribution} margin={{ top: 10, right: 12, left: -12, bottom: 8 }}><CartesianGrid stroke="#dce1e3" vertical={false} /><XAxis axisLine={false} dataKey="label" tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><YAxis allowDecimals={false} axisLine={false} tick={{ fill: "#607080", fontSize: 11 }} tickLine={false} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgba(203,104,70,0.08)" }} /><Bar animationDuration={650} dataKey="count" fill="#ae4f31" isAnimationActive={animate} name="Transactions" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame> : <section className="panel grid min-h-[430px] place-items-center p-8 text-center"><div><ShieldAlert aria-hidden="true" className="mx-auto size-7 text-accent" strokeWidth={1.5} /><span aria-hidden="true" className="mt-4 block font-mono text-[9px] text-line">04</span><p className="eyebrow mt-4">Reported cap rates</p><h2 className="mt-3 font-serif text-2xl font-medium text-navy">Insufficient sample</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate">Cap-rate statistics require at least {CAP_RATE_MINIMUM_SAMPLE} usable observations. The current filters return {data.metrics.capRateSampleSize}.</p><p className="mx-auto mt-5 max-w-xs border-t border-line pt-4 font-mono text-[10px] uppercase tracking-[0.1em] text-slate">{Math.min(data.metrics.capRateSampleSize, CAP_RATE_MINIMUM_SAMPLE)} of {CAP_RATE_MINIMUM_SAMPLE} required observations</p></div></section>}
  </div></section>;
}
