import Link from "next/link";
import { VerificationBadge } from "@/components/properties/verification-badge";
import { TableScroll } from "@/components/ui/table-scroll";
import { CAP_RATE_MINIMUM_SAMPLE, type DashboardData } from "@/lib/types";
import { formatCompactCurrency, formatCurrency, formatDate, formatNumber } from "@/lib/sample-data";

const unavailable = <span aria-label="Unavailable" className="text-slate/60">—</span>;

export function DashboardTables({ data }: { data: DashboardData }) {
  return <div className="grid gap-12">
    <section><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Largest transactions</p><h2 className="mt-3 text-3xl font-semibold text-navy">Top recorded sales</h2></div><span className="tag">Top {data.largestTransactions.length}</span></div><TableScroll className="mt-7 border border-line bg-white" label="Largest transactions, scroll horizontally if needed"><table className="w-full min-w-[850px] border-collapse text-left"><caption className="sr-only">Largest transactions within the dashboard filters</caption><thead><tr className="bg-mist text-[10px] uppercase tracking-[0.1em] text-slate"><th className="px-4 py-3" scope="col">Property</th><th className="px-4 py-3" scope="col">Market</th><th className="px-4 py-3" scope="col">Type</th><th className="px-4 py-3 text-right" scope="col">Sale price</th><th className="px-4 py-3 text-right" scope="col">Sale date</th><th className="px-4 py-3" scope="col">Status</th></tr></thead><tbody>{data.largestTransactions.map((record) => <tr className="border-t border-line" key={`${record.slug}-${record.saleDate}`}><th className="px-4 py-4 text-sm font-semibold text-navy" scope="row"><Link className="underline decoration-transparent underline-offset-4 hover:decoration-line" href={`/properties/${record.slug}`}>{record.propertyName}</Link>{record.isSample ? <span className="mt-1 block text-[9px] uppercase tracking-wider text-accent">Fictional sample</span> : null}</th><td className="px-4 py-4 text-sm text-slate">{record.market}</td><td className="px-4 py-4 text-sm text-slate">{record.propertyType}</td><td className="px-4 py-4 text-right text-sm font-semibold tabular-nums text-navy">{formatCurrency(record.salePrice)}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{formatDate(record.saleDate)}</td><td className="px-4 py-4"><VerificationBadge status={record.verificationStatus} /></td></tr>)}</tbody></table></TableScroll></section>

    <section><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Market comparison</p><h2 className="mt-3 text-3xl font-semibold text-navy">Local market summary</h2></div><span className="tag">{data.marketComparison.length} markets</span></div><TableScroll className="mt-7 border border-line bg-white" label="Local market comparison, scroll horizontally if needed"><table className="w-full min-w-[1000px] border-collapse text-left"><caption className="sr-only">Comparison of markets within the dashboard filters</caption><thead><tr className="bg-mist text-[10px] uppercase tracking-[0.1em] text-slate"><th className="px-4 py-3" scope="col">Market</th><th className="px-4 py-3 text-right" scope="col">Transactions</th><th className="px-4 py-3 text-right" scope="col">Sales volume</th><th className="px-4 py-3 text-right" scope="col">Median sale</th><th className="px-4 py-3 text-right" scope="col">Median $ / sf</th><th className="px-4 py-3 text-right" scope="col">Median cap rate</th><th className="px-4 py-3 text-right" scope="col">Avg. building size</th></tr></thead><tbody>{data.marketComparison.map((market) => <tr className="border-t border-line" key={market.market}><th className="px-4 py-4 text-sm font-semibold text-navy" scope="row">{market.market}</th><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.transactionCount}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-navy">{formatCompactCurrency(market.totalSalesVolume)}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.medianSalePrice === null ? unavailable : formatCompactCurrency(market.medianSalePrice)}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.medianPricePerSqFt === null ? unavailable : <>{formatCurrency(market.medianPricePerSqFt)} <span className="block text-[9px]">n={market.pricePerSqFtSampleSize}</span></>}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.capRateSampleSize < CAP_RATE_MINIMUM_SAMPLE || market.medianReportedCapRate === null ? <span className="text-[10px]">Suppressed · n={market.capRateSampleSize}</span> : `${(market.medianReportedCapRate * 100).toFixed(2)}%`}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.averageBuildingSize === null ? unavailable : `${formatNumber(Math.round(market.averageBuildingSize))} sf`}</td></tr>)}</tbody></table></TableScroll></section>
  </div>;
}
