import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { VerificationBadge } from "@/components/properties/verification-badge";
import { TableScroll } from "@/components/ui/table-scroll";
import { CAP_RATE_MINIMUM_SAMPLE, type DashboardData, type DashboardLargestTransaction, type DashboardMarketComparison } from "@/lib/types";
import { formatCompactCurrency, formatCurrency, formatDate, formatNumber } from "@/lib/sample-data";

const unavailable = <span aria-label="Unavailable" className="text-slate/60">—</span>;

function LargestTransactionCard({ record }: { record: DashboardLargestTransaction }) {
  return <article className="panel flex h-full flex-col p-5"><div className="flex items-start justify-between gap-3"><span className="tag">{record.propertyType}</span><VerificationBadge status={record.verificationStatus} /></div><Link className="mt-5 font-serif text-2xl font-medium leading-tight text-navy" href={`/properties/${record.slug}`}>{record.propertyName}</Link><p className="mt-2 text-xs text-slate">{record.market}</p><p className="mt-6 border-t border-line pt-4 font-serif text-3xl font-medium text-navy">{formatCurrency(record.salePrice)}</p><p className="mt-1 font-mono text-[10px] text-slate">Closed {formatDate(record.saleDate)}</p><div className="mt-auto flex items-center justify-between gap-4 pt-5">{record.isSample ? <span className="text-[9px] font-semibold uppercase tracking-[0.1em] text-accent">Fictional sample</span> : <span />}<Link className="inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.1em] text-navy hover:text-accent" href={`/properties/${record.slug}`}>Open record <ArrowRight aria-hidden="true" className="size-3.5" /></Link></div></article>;
}

function MarketCard({ market }: { market: DashboardMarketComparison }) {
  const capRateSuppressed = market.capRateSampleSize < CAP_RATE_MINIMUM_SAMPLE || market.medianReportedCapRate === null;
  const capRateValue = capRateSuppressed || market.medianReportedCapRate === null ? "Suppressed" : `${(market.medianReportedCapRate * 100).toFixed(2)}%`;
  return <article className="panel p-5"><div className="flex items-start justify-between gap-4"><h3 className="font-serif text-2xl font-medium text-navy">{market.market}</h3><span className="tag">n = {market.transactionCount}</span></div><p className="mt-5 border-y border-line py-4 font-serif text-3xl font-medium text-navy">{formatCompactCurrency(market.totalSalesVolume)}<span className="mt-1 block font-sans text-[9px] font-semibold uppercase tracking-[0.1em] text-slate">Total recorded volume</span></p><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-5"><div><dt className="text-[9px] uppercase tracking-[0.08em] text-slate">Median sale</dt><dd className="mt-1 text-sm font-medium text-navy">{market.medianSalePrice === null ? unavailable : formatCompactCurrency(market.medianSalePrice)}</dd></div><div><dt className="text-[9px] uppercase tracking-[0.08em] text-slate">Median $ / sf</dt><dd className="mt-1 text-sm font-medium text-navy">{market.medianPricePerSqFt === null ? unavailable : formatCurrency(market.medianPricePerSqFt)}</dd><dd className="font-mono text-[9px] text-slate">n = {market.pricePerSqFtSampleSize}</dd></div><div><dt className="text-[9px] uppercase tracking-[0.08em] text-slate">Median cap rate</dt><dd className="mt-1 text-sm font-medium text-navy">{capRateValue}</dd><dd className="font-mono text-[9px] text-slate">n = {market.capRateSampleSize}</dd></div><div><dt className="text-[9px] uppercase tracking-[0.08em] text-slate">Avg. building</dt><dd className="mt-1 text-sm font-medium text-navy">{market.averageBuildingSize === null ? unavailable : `${formatNumber(Math.round(market.averageBuildingSize))} sf`}</dd></div></dl></article>;
}

export function DashboardTables({ data }: { data: DashboardData }) {
  return <div className="grid gap-14">
    <section aria-labelledby="largest-sales-title"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Largest transactions</p><h2 className="mt-3 font-serif text-3xl font-medium text-navy" id="largest-sales-title">Top recorded sales</h2><p className="mt-2 text-xs text-slate">Ranked by recorded sale consideration inside the current filters.</p></div><span className="tag">Top {data.largestTransactions.length}</span></div><TableScroll className="mt-7 hidden border border-line bg-white shadow-[0_16px_42px_rgba(7,26,44,0.05)] lg:block" label="Largest transactions, scroll horizontally if needed"><table className="w-full min-w-[850px] border-collapse text-left"><caption className="sr-only">Largest transactions within the dashboard filters</caption><thead><tr className="bg-mist text-[10px] uppercase tracking-[0.1em] text-slate"><th className="px-4 py-3" scope="col">Property</th><th className="px-4 py-3" scope="col">Market</th><th className="px-4 py-3" scope="col">Type</th><th className="px-4 py-3 text-right" scope="col">Sale price</th><th className="px-4 py-3 text-right" scope="col">Sale date</th><th className="px-4 py-3" scope="col">Status</th></tr></thead><tbody>{data.largestTransactions.map((record) => <tr className="group border-t border-line transition-colors hover:bg-mist/35" key={`${record.slug}-${record.saleDate}`}><th className="px-4 py-4 text-sm font-semibold text-navy" scope="row"><Link className="underline decoration-transparent underline-offset-4 group-hover:decoration-accent" href={`/properties/${record.slug}`}>{record.propertyName}</Link>{record.isSample ? <span className="mt-1 block text-[9px] uppercase tracking-wider text-accent">Fictional sample</span> : null}</th><td className="px-4 py-4 text-sm text-slate">{record.market}</td><td className="px-4 py-4 text-sm text-slate">{record.propertyType}</td><td className="px-4 py-4 text-right font-serif text-lg font-medium tabular-nums text-navy">{formatCurrency(record.salePrice)}</td><td className="px-4 py-4 text-right font-mono text-xs tabular-nums text-slate">{formatDate(record.saleDate)}</td><td className="px-4 py-4"><VerificationBadge status={record.verificationStatus} /></td></tr>)}</tbody></table></TableScroll><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:hidden">{data.largestTransactions.map((record) => <LargestTransactionCard key={`${record.slug}-${record.saleDate}`} record={record} />)}</div></section>

    <section aria-labelledby="market-summary-title"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Market comparison</p><h2 className="mt-3 font-serif text-3xl font-medium text-navy" id="market-summary-title">Local market summary</h2><p className="mt-2 text-xs text-slate">Missing values remain unavailable, and cap rates stay suppressed below the sample threshold.</p></div><span className="tag">{data.marketComparison.length} markets</span></div><TableScroll className="mt-7 hidden border border-line bg-white shadow-[0_16px_42px_rgba(7,26,44,0.05)] lg:block" label="Local market comparison, scroll horizontally if needed"><table className="w-full min-w-[1000px] border-collapse text-left"><caption className="sr-only">Comparison of markets within the dashboard filters</caption><thead><tr className="bg-mist text-[10px] uppercase tracking-[0.1em] text-slate"><th className="px-4 py-3" scope="col">Market</th><th className="px-4 py-3 text-right" scope="col">Transactions</th><th className="px-4 py-3 text-right" scope="col">Sales volume</th><th className="px-4 py-3 text-right" scope="col">Median sale</th><th className="px-4 py-3 text-right" scope="col">Median $ / sf</th><th className="px-4 py-3 text-right" scope="col">Median cap rate</th><th className="px-4 py-3 text-right" scope="col">Avg. building size</th></tr></thead><tbody>{data.marketComparison.map((market) => <tr className="border-t border-line transition-colors hover:bg-mist/35" key={market.market}><th className="px-4 py-4 text-sm font-semibold text-navy" scope="row">{market.market}</th><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.transactionCount}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-navy">{formatCompactCurrency(market.totalSalesVolume)}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.medianSalePrice === null ? unavailable : formatCompactCurrency(market.medianSalePrice)}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.medianPricePerSqFt === null ? unavailable : <>{formatCurrency(market.medianPricePerSqFt)} <span className="block font-mono text-[9px]">n={market.pricePerSqFtSampleSize}</span></>}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.capRateSampleSize < CAP_RATE_MINIMUM_SAMPLE || market.medianReportedCapRate === null ? <span className="text-[10px]">Suppressed · n={market.capRateSampleSize}</span> : `${(market.medianReportedCapRate * 100).toFixed(2)}%`}</td><td className="px-4 py-4 text-right text-sm tabular-nums text-slate">{market.averageBuildingSize === null ? unavailable : `${formatNumber(Math.round(market.averageBuildingSize))} sf`}</td></tr>)}</tbody></table></TableScroll><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:hidden">{data.marketComparison.map((market) => <MarketCard key={market.market} market={market} />)}</div></section>
  </div>;
}
