import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/container";
import { ValueRow } from "@/components/properties/value-row";
import { VerificationBadge } from "@/components/properties/verification-badge";
import { TableScroll } from "@/components/ui/table-scroll";
import { getPropertyBySlug } from "@/lib/data/properties";
import { calculateCapRate, calculatePricePerSquareFoot } from "@/lib/property-utils";
import { formatCurrency, formatDate, formatNumber, sampleProperties } from "@/lib/sample-data";
import type { ValueKind } from "@/lib/types";

type PageProps = { params: Promise<{ slug: string }> };

export function generateStaticParams() { return sampleProperties.map((property) => ({ slug: property.slug })); }

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const property = await getPropertyBySlug(slug);
  if (!property) return { title: "Property not found", robots: { index: false, follow: false } };
  const description = `${property.propertyType} transaction research for ${property.city}, ${property.state}.`;
  return { title: property.propertyName, description, alternates: { canonical: `/properties/${slug}` }, robots: property.isSample ? { index: false, follow: false } : undefined, openGraph: { title: property.propertyName, description, url: `/properties/${slug}`, type: "website", images: [{ url: "/og.png", width: 1732, height: 996, alt: "Mid-Atlantic CRE Intelligence" }] } };
}

export default async function PropertyDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const property = await getPropertyBySlug(slug);
  if (!property) notFound();
  const latest = property.transactions.toSorted((a, b) => b.saleDate.localeCompare(a.saleDate))[0] ?? null;
  const calculatedPsf = latest ? calculatePricePerSquareFoot(latest.salePrice, property.buildingSqFt) : null;
  const calculatedCapRate = latest ? calculateCapRate(latest.reportedNoi, latest.salePrice, latest.verificationStatus === "Verified") : null;
  const reportedKind: ValueKind = latest?.verificationStatus === "Estimated" ? "Estimated" : "Reported";
  const hasCoordinates = property.latitude !== null && property.longitude !== null;
  const mapUrl = hasCoordinates ? `https://www.openstreetmap.org/?mlat=${property.latitude}&mlon=${property.longitude}#map=17/${property.latitude}/${property.longitude}` : null;

  return <><section className="detail-hero"><Container className="relative z-10 py-12 sm:py-18"><Link className="back-link-dark" href="/properties"><span aria-hidden="true">←</span> Back to database</Link><div className="mt-9 grid gap-10 lg:grid-cols-[1fr_0.42fr] lg:items-end"><div>{property.isSample ? <span className="tag border-white/20 bg-white/10 text-[#efb091]">Fictional sample property</span> : <span className="tag border-white/20 bg-white/10 text-white/75">Public research record</span>}<h1 className="mt-5 max-w-4xl font-serif text-4xl font-semibold leading-[1.05] tracking-[-0.04em] text-white sm:text-6xl">{property.propertyName}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/65 sm:text-lg">{property.streetAddress}<span aria-hidden="true"> · </span>{property.city}, {property.state} {property.zipCode}</p><div className="mt-7 flex flex-wrap items-center gap-3"><span className="tag border-white/20 bg-transparent text-white/75">{property.propertyType}</span>{latest ? <VerificationBadge status={latest.verificationStatus} /> : <span className="tag border-white/20 bg-transparent text-white/70">No transaction</span>}</div></div><aside className="detail-hero-card"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#d98b68]">Record disclosure</p><p className="mt-4 text-sm leading-7 text-white/68">{property.isSample ? "All names, addresses, tenants, and financial values on this page are fictional placeholders for development." : "Review every source and verification status before relying on a material value."}</p><dl className="mt-5 grid grid-cols-2 gap-4 border-t border-white/15 pt-5"><div><dt className="text-[9px] uppercase tracking-wider text-white/40">Sources</dt><dd className="mt-1 font-serif text-2xl text-white">{property.sources.length}</dd></div><div><dt className="text-[9px] uppercase tracking-wider text-white/40">Transactions</dt><dd className="mt-1 font-serif text-2xl text-white">{property.transactions.length}</dd></div></dl></aside></div></Container></section>

  <Container className="grid gap-12 py-16 lg:grid-cols-[1.45fr_0.55fr]">
    <div className="grid gap-14">
      <section><p className="section-rule">Overview</p><h2 className="mt-4 font-serif text-3xl font-semibold tracking-tight text-navy">Property profile</h2><p className="mt-5 max-w-3xl text-base leading-7 text-slate">{property.description}</p><dl className="mt-8 border-t-2 border-navy"><ValueRow label="Property type" value={property.propertyType} /><ValueRow label="County" value={property.county} /><ValueRow label="Map location" value={mapUrl ? <a aria-label={`View ${property.propertyName} on OpenStreetMap (opens in a new tab)`} className="inline-flex flex-col underline decoration-line underline-offset-4 hover:text-accent" href={mapUrl} rel="noreferrer" target="_blank"><span>View on OpenStreetMap</span><span className="mt-1 font-mono text-[11px] font-normal text-slate">{property.latitude?.toFixed(6)}, {property.longitude?.toFixed(6)}</span></a> : null} /></dl></section>

      <section><p className="eyebrow">Latest transaction</p><h2 className="mt-3 text-3xl font-semibold text-navy">Transaction information</h2>{latest ? <dl className="mt-7 border-t border-line"><ValueRow label="Sale date" value={formatDate(latest.saleDate)} /><ValueRow label="Sale price" value={formatCurrency(latest.salePrice)} kind={reportedKind} /><ValueRow label="Buyer" value={latest.buyer} kind={reportedKind} /><ValueRow label="Seller" value={latest.seller} kind={reportedKind} /><ValueRow label="Reported cap rate" value={latest.reportedCapRate ? `${(latest.reportedCapRate * 100).toFixed(2)}%` : null} kind={reportedKind} /><ValueRow label="Reported NOI" value={latest.reportedNoi ? formatCurrency(latest.reportedNoi) : null} kind={reportedKind} /><ValueRow label="Price per square foot" value={calculatedPsf ? formatCurrency(calculatedPsf) : null} kind="Calculated" /><ValueRow label="Calculated cap rate" value={calculatedCapRate ? `${(calculatedCapRate * 100).toFixed(2)}%` : null} kind="Calculated" /><ValueRow label="Transaction type" value={latest.transactionType} /></dl> : <p className="mt-5 text-sm text-slate">No transaction record is available. No values have been estimated.</p>}<p className="mt-5 border-l-2 border-line pl-4 text-xs leading-5 text-slate">Calculated cap rate remains unavailable unless both NOI and property value have verified status. Price per square foot is calculated from sale price ÷ building area.</p></section>

      <section><p className="section-rule">Physical record</p><h2 className="mt-4 font-serif text-3xl font-semibold tracking-tight text-navy">Property details</h2><dl className="mt-7 grid border-t-2 border-navy sm:grid-cols-2 sm:gap-x-10"><ValueRow label="Building area" value={property.buildingSqFt ? `${formatNumber(property.buildingSqFt)} sq. ft.` : null} /><ValueRow label="Lot acreage" value={property.lotAcres ? formatNumber(property.lotAcres) : null} /><ValueRow label="Year built" value={property.yearBuilt} /><ValueRow label="Renovation year" value={property.yearRenovated} /><ValueRow label="Floors" value={property.numberOfFloors} /><ValueRow label="Parking spaces" value={property.parkingSpaces} /><ValueRow label="Major tenants" value={property.majorTenants.length ? property.majorTenants.join(", ") : null} /><ValueRow label="Lease structure" value={property.leaseStructure} /></dl></section>

      {property.transactions.length > 1 ? <section><p className="eyebrow">Transaction history</p><h2 className="mt-3 text-3xl font-semibold text-navy">Recorded sales</h2><TableScroll className="mt-7 border border-line" label="Property transaction history, scroll horizontally if needed"><table className="w-full min-w-[650px] text-left"><thead className="bg-mist text-[10px] uppercase tracking-wider text-slate"><tr><th className="px-4 py-3" scope="col">Date</th><th className="px-4 py-3" scope="col">Price</th><th className="px-4 py-3" scope="col">Buyer</th><th className="px-4 py-3" scope="col">Seller</th><th className="px-4 py-3" scope="col">Status</th></tr></thead><tbody>{property.transactions.toSorted((a, b) => b.saleDate.localeCompare(a.saleDate)).map((transaction) => <tr className="border-t border-line text-sm" key={transaction.id}><td className="px-4 py-4 text-slate">{formatDate(transaction.saleDate)}</td><td className="px-4 py-4 font-semibold text-navy">{formatCurrency(transaction.salePrice)}</td><td className="px-4 py-4 text-slate">{transaction.buyer ?? "Unavailable"}</td><td className="px-4 py-4 text-slate">{transaction.seller ?? "Unavailable"}</td><td className="px-4 py-4"><VerificationBadge status={transaction.verificationStatus} /></td></tr>)}</tbody></table></TableScroll></section> : null}

      <section><p className="eyebrow">Source record</p><h2 className="mt-3 text-3xl font-semibold text-navy">Sources</h2>{property.sources.length ? <div className="mt-7 grid gap-4">{property.sources.map((source) => <article className="panel p-5" key={source.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold text-navy">{source.sourceName}</h3><p className="mt-1 text-xs text-slate">{source.sourceType}{source.publicationDate ? ` · Published ${formatDate(source.publicationDate)}` : ""} · Accessed {formatDate(source.accessedDate)}</p></div>{source.isSample ? <span className="tag text-accent">Placeholder citation</span> : <a aria-label={`Open source: ${source.sourceName} (opens in a new tab)`} className="text-sm font-semibold text-navy underline decoration-line underline-offset-4" href={source.sourceUrl} rel="noreferrer" target="_blank">Open source</a>}</div>{source.notes ? <p className="mt-4 text-sm leading-6 text-slate">{source.notes}</p> : null}</article>)}</div> : <p className="mt-5 text-sm text-slate">No sources are attached. This record should be treated as incomplete.</p>}</section>
    </div>
    <aside><div className="sticky top-28 panel p-6"><p className="eyebrow">Record quality</p><dl className="mt-5 grid gap-4"><div><dt className="text-xs text-slate">Verification</dt><dd className="mt-2">{latest ? <VerificationBadge status={latest.verificationStatus} /> : "Unavailable"}</dd></div><div className="border-t border-line pt-4"><dt className="text-xs text-slate">Date verified</dt><dd className="mt-1 text-sm font-semibold text-navy">{latest?.dateVerified ? formatDate(latest.dateVerified) : "Unavailable"}</dd></div><div className="border-t border-line pt-4"><dt className="text-xs text-slate">Sources attached</dt><dd className="mt-1 text-sm font-semibold text-navy">{property.sources.length}</dd></div><div className="border-t border-line pt-4"><dt className="text-xs text-slate">Last updated</dt><dd className="mt-1 text-sm font-semibold text-navy">{formatDate(property.updatedAt)}</dd></div></dl><Link className="button-secondary mt-7 w-full" href="/methodology">Review methodology</Link></div></aside>
  </Container></>;
}
