import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { PageHero } from "@/components/ui/page-hero";

export const metadata: Metadata = { title: "About", description: "About the independent student research project behind Mid-Atlantic CRE Intelligence.", alternates: { canonical: "/about" } };
const sections = [
  ["Why it was created", "Commercial real estate information is often fragmented across public records, local reporting, filings, and market commentary. This project explores how careful sourcing and consistent definitions can make that information easier to understand."],
  ["About the founder", "The platform is maintained by a student researcher interested in commercial property markets, transaction analysis, urban economics, and responsible data communication. Personal details are intentionally limited."],
  ["Research interests", "Areas of focus include local transaction patterns, pricing metrics, property-sector fundamentals, capital markets, tenant activity, and the practical limits of public CRE data."],
];

export default function AboutPage() {
  const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim();
  return <><PageHero eyebrow="About the project" title="Independent research, built in public." description="A student-led platform for organizing local commercial real estate evidence and explaining what the data can—and cannot—support." disclosure="The platform publishes no confidential or proprietary internship information and is not affiliated with an industry firm." />
    <Container className="grid gap-12 py-16 lg:grid-cols-[0.42fr_1fr] lg:py-20"><aside><div className="overflow-hidden bg-navy text-white shadow-[0_20px_50px_rgba(11,34,57,0.16)]"><div className="border-b border-white/15 px-6 py-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#d98b68]">Project profile</p></div><dl><div className="border-b border-white/10 px-6 py-5"><dt className="text-[9px] font-bold uppercase tracking-wider text-white/68">Region</dt><dd className="mt-2 font-serif text-xl">MD · D.C. · Northern VA</dd></div><div className="border-b border-white/10 px-6 py-5"><dt className="text-[9px] font-bold uppercase tracking-wider text-white/68">Status</dt><dd className="mt-2 text-sm font-semibold">Independent student project</dd></div><div className="px-6 py-5"><dt className="text-[9px] font-bold uppercase tracking-wider text-white/68">Purpose</dt><dd className="mt-2 text-sm font-semibold">Education and research</dd></div></dl></div></aside>
      <div className="grid gap-12">{sections.map(([title, copy], index) => <section className="grid gap-4 border-t-2 border-navy pt-5 sm:grid-cols-[54px_1fr]" key={title}><span className="font-serif text-3xl font-semibold text-accent">0{index + 1}</span><div className="prose-section"><h2>{title}</h2><p>{copy}</p></div></section>)}<section className="relative overflow-hidden border border-accent/25 bg-accent-soft p-7 shadow-[0_18px_44px_rgba(11,34,57,0.08)] sm:p-10"><span aria-hidden="true" className="absolute right-6 top-2 font-serif text-8xl text-white/70">“</span><p className="eyebrow">Independence statement</p><p className="relative mt-6 max-w-3xl font-serif text-2xl font-semibold leading-9 text-navy">Mid-Atlantic CRE Intelligence is an independent student research project and is not affiliated with any brokerage, investment firm, property owner, or data provider.</p><p className="mt-5 text-sm font-bold text-slate">No confidential or proprietary internship information is published on this website.</p></section><section className="prose-section border-t-2 border-navy pt-6"><h2>Contact</h2>{contactEmail ? <p>Professional inquiries may be directed to <a className="font-semibold text-navy underline decoration-accent/50 underline-offset-4 hover:decoration-accent" href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p> : <p>Contact information will be published when the production address is configured. No private personal information is displayed.</p>}</section></div>
    </Container>
  </>;
}
