import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { PageHero } from "@/components/ui/page-hero";

export const metadata: Metadata = { title: "Methodology", description: "Data collection, verification, calculation methods, and limitations for Mid-Atlantic CRE Intelligence.", alternates: { canonical: "/methodology" } };
const methods = [
  ["Geographic coverage", "Maryland, Washington, D.C., and Northern Virginia. Coverage is selective and does not represent every transaction in the region."],
  ["Data collection", "Records will be assembled from public records, government databases, company announcements, credible journalism, regulatory filings, and other attributable public sources."],
  ["Verification criteria", "Material transaction details are evaluated source by source. Conflicting figures remain flagged until resolved; missing figures remain missing."],
  ["Calculations", "Price per square foot equals sale price divided by building square feet. Cap rate is calculated only when both verified NOI and property value are available."],
  ["Missing-data treatment", "Unavailable values are displayed as unavailable, not inferred. Estimated, reported, and calculated values are labeled separately."],
  ["Update frequency", "The production database is intended to be reviewed periodically, with access and verification dates preserved for each source."],
];
const statuses = [["Verified", "Supported by at least two credible sources."], ["Single Source", "Supported by one credible source."], ["Estimated", "Derived from available figures and labeled as an estimate."], ["Incomplete", "One or more material fields are unavailable."]];

export default function MethodologyPage() {
  return <><PageHero eyebrow="Research standards" title="Methodology before metrics." description="The platform makes sourcing, calculation choices, uncertainty, and research limits visible alongside every finding." disclosure="Values remain unavailable when the public evidence cannot support them. The database does not fill gaps with invented assumptions." />
    <Container className="py-16 lg:py-20"><div className="grid gap-5 md:grid-cols-2">{methods.map(([title, copy], index) => <section className="panel relative min-h-56 overflow-hidden p-6 sm:p-8" key={title}><span aria-hidden="true" className="absolute right-5 top-3 font-serif text-6xl font-semibold text-mist">0{index + 1}</span><p className="eyebrow">Method {String(index + 1).padStart(2, "0")}</p><h2 className="relative mt-5 font-serif text-3xl font-semibold text-navy">{title}</h2><p className="relative mt-4 max-w-xl text-sm leading-7 text-slate">{copy}</p></section>)}</div></Container>
    <section className="bg-navy py-16 text-white lg:py-20"><Container><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d98b68]">Verification scale</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="font-serif text-4xl font-semibold sm:text-5xl">Four visible states</h2><p className="max-w-md text-sm leading-6 text-[#b9c5ce]">Status labels describe the strength and completeness of the public evidence, not the quality of the asset.</p></div><div className="mt-10 grid border-l border-t border-white/15 md:grid-cols-4">{statuses.map(([status, meaning], index) => <div className="border-b border-r border-white/15 p-6" key={status}><span className="font-serif text-xl text-white/25">0{index + 1}</span><h3 className="mt-5 font-serif text-2xl font-semibold">{status}</h3><p className="mt-3 text-sm leading-6 text-[#b9c5ce]">{meaning}</p></div>)}</div></Container></section>
    <Container className="py-16 lg:py-20"><section className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow">Limitations & disclosure</p><h2 className="mt-4 font-serif text-4xl font-semibold leading-tight text-navy">Read every number in context</h2></div><div className="prose-section"><ul><li>The database does not represent every transaction in the region.</li><li>Cap rates and NOI are often unavailable or confidential.</li><li>Public records may be delayed, incomplete, or revised.</li><li>The website is for educational and research purposes.</li><li>The content is not investment advice.</li><li>Potential conflicts will be disclosed; no confidential or proprietary internship information is used.</li></ul></div></section></Container>
  </>;
}
